server:
  port: 7140
  servlet:
    context-path: /message
spring:
  main:
    banner-mode: 'off'
  application:
    name: hk-message
  boot:
    admin:
      client:
        url: "http://127.0.0.1:9999"
        instance:
          prefer-ip: false
          service-url: "http://127.0.0.1:${server.port}"
  servlet:
    multipart:
      enabled: false # 禁用文件上传功能
  mvc:
    throw-exception-if-no-handler-found: true
######################################################### 国际化配置
  messages:
    encoding: UTF-8
    basename: org/springframework/security/messages,com/hk/core/i18n/messages,messages
    cache-duration: -1ms
######################################################### thymeleaf 配置
  thymeleaf:
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html; charset=utf-8
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
######################################################### datasource 配置
  datasource:
    name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hk_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: root
######################################################### hikari datasource 配置
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
      minimum-idle: 10
      connection-timeout: 30000
      read-only: false
      connection-test-query: SELECT 1 FROM DUAL