version: "3"
services:
  oauth2-server:
    build: .
    image: oauth2-server
    container_name: oauth2-server
    ports:
      - "8086:8086"
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/docker/springcloud/oauth2-server:/app:ro"
    command:
      - "-Xms256m"
      - "-Xmx256m"
      - "hk-sso-server-2.1.0.RELEASE.jar"
    restart: "always"