server:
  port: 8771
  servlet:
    context-path: /

spring:
  application:
    name: hk-gateway-zuul
  aop:
    proxy-target-class: true
################################################################## eureka配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
################################################################## zuul 配置
zuul:
  add-proxy-headers: true
  routes:
    hk-emi:
      path: /emi/**
      sensitiveHeaders: "*"

    hk-pms:
      path: /pms/**
      sensitiveHeaders: "*"

    hk-sso-server:
      path: /oauth2/**
      sensitiveHeaders: "*"

################################################################## ribbon configuration
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

################################################################## logging configuration
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.cloud.netflix.zuul: debug
