server:
  servlet:
    context-path: /
    session:
      timeout: 30ms
      cookie:
        name: auth_jsession
        http-only: true
##########################################################
spring:
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      enabled: false # 禁用文件上传功能
  mvc:
    throw-exception-if-no-handler-found: true
######################################################### 国际化配置
  messages:
    encoding: UTF-8
    basename: org/springframework/security/messages,com/hk/core/i18n/messages,messages
    cache-duration: -1ms
######################################################### thymeleaf 配置
  thymeleaf:
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html; charset=utf-8
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
######################################################### jpa 配置
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
      # hbm2ddl:
      # auto: upload
        enable_lazy_load_no_trans: true # 解决懒加载在非事务中的 no-session 的问题 @see https://stackoverflow.com/questions/36583185/spring-data-jpa-could-not-initialize-proxy-no-session-with-methods-marke
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
######################################################### datasource 配置
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hk_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: root
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2
      filter:
        stat:
          slow-sql-millis: 5000
      connection-properties: druid.stat.mergeSql=true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        allow: 127.0.0.1
        login-username: druidAdmin
        login-password: druidAdmin@%*
      web-stat-filter:
        enabled: true
        url-pattern: /**
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
################################################################### redis
  redis:
    password: 1234567
    host: 127.0..0.1
    port: 6379
    database: 2
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
  cache:
    type: redis
######################################################### eureka 配置
eureka:
  instance:
    prefer-ip-address: false
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://root:root123@127.0.0.1:8761/eureka

######################################################### mybatis 配置
mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

######################################################### mybatis pageHelper 配置
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

######################################################### spring security oauth2 配置
security:
  oauth2:
    authorization:
      token-key-access: "isAuthenticated()"
      check-token-access: "isAuthenticated()"

hk:
  authentication:
    browser:
      login-url: /login
      login-processing-url: /login
      logout-url: /logout
      logout-success-url: /
      username-parameter: username
      password-parameter: password
      maximum-sessions: 2
    sms:
      enabled: true
      code-length: 6
      code-expire-in: 180
      code-parameter: phoneCode
      phone-parameter: phone
      post-only: true
      phone-login-uri: /mobile/login

######################################################### 微信配置
wechat:
  mp:
    app-id: wx72303d4d8b1f0d00   #微信网页二维码登陆需要在微信开放平台申请账号并审核，公众平台的app-id无效
    secret: 19175e5d7111969a1dcc86048d338f866
#    token: hk9060   #此token对于微信网页二微码登陆无效
  qrcode:
    callback-url: /wechat/callback
    call-host: http://sqn62q.natappfree.cc
    state: 3d6be0a4685d839573b04816624a415e


######################################################### logging 配置
logging:
  level:
    root: error
    org.springframework.security: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    com.hk: debug







