server:
  port: 8770
  servlet:
    context-path: /
spring:
  main:
    banner-mode: 'off'
  application:
    name: hk-config-server
  profiles:
    active: native
  cloud:
    config:
      enabled: true
      name: ${spring.application.name}
      server:
        native:
          search-locations:
            - "file:///E:/worksplace/hk/github/hk-config/platform-config"
#          - "file:///Users/huangkai/worksplace/hk-config/platform-config"
#        git:
#          uri: https://github.com/huankai/hk-config.git
#          search-paths:
##           会在此目录下查询配置文件
#          - "platform-config"
##           clone 分支
#          default-label: "2.1.2.RELEASE"
##           clone 的项目保存在指定的目录中
#          basedir: "/config-basedir" 

##    stream:
##      kafka:
##        binder:
##          brokers:
##            - "sjq128:9092"
##            - "sjq129:9092"
##            - "sjq130:9092"
########################### spring boot admin client configuration ######################################################
  boot:
    admin:
      client:
        username: user
        password: user#1350
        url: "http://127.0.0.1:8780"
        instance:
          prefer-ip: false
          service-url: "http://127.0.0.1:${server.port}"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
###########################   log4j2 configuration ######################################################
logging:
  config: classpath:log4j2.xml
