version: "3"
services:
  eureka-server:
   # 指定 Dockerfile文件路径
    build: .
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/docker/springcloud/eureka-server:/app:ro"
    command:
      - "-Xms256m"
      - "-Xmx256m"
      - "hk-discover-eureka-2.1.0.RELEASE.jar"
    restart: "always"