server:
  port: 8771
spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  application:
    name: hk-spring-cloud-gateway
  autoconfigure:
    exclude:
      # 默认情况下，spring boot web 应用会装配一些功能组件 bean,大多数情况下，可以选择性关闭自动装配的组件bean,以提升性能。
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration
      - org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration
  mvc:
    formcontent:
      filter:
        enabled: false
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
#      default-filters:

      routes:
        - id: hk-emi
          uri: http://127.0.0.1:7120
          predicates:
            - Path=/emi/**
#          filters:
#            - StripPrefix=1
        - id: hk-pms
          uri: http://127.0.0.1:7110
          predicates:
            - Path=/pms/**
#          filters:
#            - StripPrefix=1
        - id: hk-oauth2
          uri: http://127.0.0.1:7100
          predicates:
#          Path Route Predicate 会解析成  org.springframework.cloud.gateway.handler.predicate.PathRoutePredicateFactory 进行处理
#          表示url路径匹配 ，当请求以 oauth2开头时，会　route 到  http://127.0.0.1:7100
#           其它 predicates 可查看文档: https://blog.csdn.net/forezp/article/details/84926662
#           spring cloud 文档: https://blog.csdn.net/forezp/article/details/70148833
            - Path=/oauth2/**
          filters:
#            - StripPrefix=1
            - name: RequestRateLimiter
              args:
#              用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter:
#                令牌桶每秒填充平均速率
                  replenish-rate: 1
#                 令牌桶总容量hostAddrKeyResolver
                  burst-capacity: 3
    nacos:
      discovery:
        server-addr: 182.61.40.18:8848
        namespace: eae427cd-ecb0-49fd-b3f1-999a0d68d2fe
  ############# 使用 redis 限流
  redis:
    host: 192.168.64.128
    database: 5

logging:
  level:
    root: error
    com.hk.springcloud.gateway: info
    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: debug
#    org.springframework.web.reactive: debug
