server:
  port: 8771
  servlet:
    context-path: /

spring:
  application:
    name: hk-gateway-zuul

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

zuul:
  add-proxy-headers: true
  routes:
    hk-emi:
      path: /emi/**
      sensitiveHeaders: "*"

    hk-pms:
      path: /pms/**
      sensitiveHeaders: "*"

    hk-sso-server:
      path: /sso/**
      sensitiveHeaders: "*"

security:
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:${server.port}/sso/oauth/token
      user-authorization-uri: http://127.0.0.1:${server.port}/sso/oauth/authorize
      client-id: browser
    resource:
      user-info-uri: http://127.0.0.1:${server.port}/sso/user
      prefer-token-info: false

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
