server:
  port: 7140
  servlet:
    context-path: /message
spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  application:
    name: hk-message
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
######################################################### 国际化配置
  messages:
    encoding: UTF-8
    basename: messages,com/hk/core/i18n/messages,org/springframework/security/messages
    cache-duration: -1ms
######################################################### datasource 配置
  datasource:
    name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hk_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: root
######################################################### hikari datasource 配置
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
      minimum-idle: 10
      connection-timeout: 30000
      read-only: false
      connection-test-query: SELECT 1 FROM DUAL