server:
  port: 8772
  servlet:
    context-path: /

spring:
  application:
    name: hk-emi
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
      # hbm2ddl:
      # auto: upload
        enable_lazy_load_no_trans: true # 解决懒加载在非事务中的 no-session 的问题 @see https://stackoverflow.com/questions/36583185/spring-data-jpa-could-not-initialize-proxy-no-session-with-methods-marke
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hk_emi?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: root
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter-class-names:
      - stat
      - wall
      - log4j2
#################################################################### consul
#  cloud:
#    consul:
#      port: 8500
#      host: 192.168.64.128
#      discovery:
#        service-name: ${spring.application.name}

#################################################################### redis
  redis:
#    password: 1234567
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 0ms
    jedis:
      pool:
        max-wait: -1ms
        max-idle: 100
        max-active: 1000
        min-idle: 100
  cache:
    type: redis
#      connect-properties:
#        druid.stat.mergeSql: true
#        druid.stat.slowSqlMillis: 5000


#################################################################### eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


################################################################### oauth2
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://127.0.0.1:8080/auth/user
      prefer-token-info: false

################################################################### logging
logging:
  level:
    root: info
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug
