server:
  port: 8772
  servlet:
    context-path: /

spring:
  application:
    name: hk-emi

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.1.76:8761/eureka