server:
  port: 8772
  servlet:
    context-path: /
    session:
      cookie:
        name: EMSESSION

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  messages:
      basename: org/springframework/security/messages,com/hk/core/i18n/messages,messages
      encoding: utf-8
      cache-duration: -1ms
  application:
    name: hk-emi
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
      # hbm2ddl:
      # auto: upload
        enable_lazy_load_no_trans: true # 解决懒加载在非事务中的 no-session 的问题 @see https://stackoverflow.com/questions/36583185/spring-data-jpa-could-not-initialize-proxy-no-session-with-methods-marke
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hk_emi?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: root
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2
      filter:
        stat:
          slow-sql-millis: 5000
      connection-properties: druid.stat.mergeSql=true,druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        allow: 127.0.0.1
        login-username: druidAdmin
        login-password: druidAdmin@%*
      web-stat-filter:
        enabled: true
        url-pattern: /**
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#################################################################### consul
#  cloud:
#    consul:
#      port: 8500
#      host: 192.168.64.128
#      discovery:
#        service-name: ${spring.application.name}

#################################################################### redis
  redis:
    password: 1234567
    host: 192.168.64.128
    port: 6379
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
  cache:
    type: redis

#################################################################### eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


################################################################### oauth2
security:
  oauth2:
    client:
      client-id: 4028c0816371a097016371a38d5a0000
      client-secret: 4028c0816371a097016371a38d5a0000
      user-authorization-uri: http://127.0.0.1:8080/oauth/authorize
      access-token-uri: http://127.0.0.1:8080/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/oauth/token_key
hk:
  authentication:
    browser:
      logout-url: /logout
      logout-success-url: http://127.0.0.1:8080/oauth/logout?redirect_url=http://127.0.0.1:8772/index
################################################################### logging
logging:
  level:
    root: error
    org.springframework: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    com.hk: debug
