server:
  port: 8780
  servlet:
    context-path: /
spring:
  main:
    banner-mode: 'off'
  application:
    name: hk-springboot-admin-server
  security:
    user:
      # 登陆用户名
      name: user
      # 登陆密码
      password: user#1350
######################################################### eureka 配置
eureka:
  instance:
    prefer-ip-address: false
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://root:root123@127.0.0.1:8761/eureka-server/eureka
logging:
  config: 'classpath:log4j2.xml'