server:
  port: 8780
  servlet:
    context-path: /admin
  undertow:
    worker-threads: 256
    io-threads: 16
    buffer-size: 1024
    direct-buffers: true
spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  application:
    name: hk-springboot-admin-server
  security:
    user:
      # 登陆用户名
      name: user
      # 登陆密码
      password: user#1350
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.40.18:8848
        namespace: eae427cd-ecb0-49fd-b3f1-999a0d68d2fe
logging:
  config: 'classpath:log4j2.xml'