server:
  port: 7200
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  application:
    name: hk-platform-web
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration
      - org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
    formcontent:
      filter:
        enabled: false
  resources:
    add-mappings: true
  messages:
    encoding: UTF-8
    cache-duration: -1ms
    basename: messages,com/hk/core/i18n/messages,org/springframework/security/messages
######################################################### thymeleaf 配置
  thymeleaf:
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html; charset=utf-8
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
######################################################### datasource 配置
  datasource:
    name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.64.128:3306/hk_platform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
      minimum-idle: 10
      connection-timeout: 30000
      read-only: false
      connection-test-query: SELECT 1
  cache:
    type: redis
######################################################### redis 配置
  redis:
    host: 182.61.40.18
    password: redisa$min302
    port: 6350
    database: 2
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
######################################################### mybatis 配置
mybatis:
  mapper-locations: classpath*:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

######################################################### security 配置
hk:
  authentication:
    allow-session-creation: true
    login:
      login-url: /login
      login-processing-url: /login
      logout-url: /logout
      logout-success-url: ${server.servlet.context-path}
      username-parameter: username
      password-parameter: password
      maximum-sessions: 2
######################################################### log 配置
logging:
  config: 'classpath:log4j2.xml'


