server:
  port: 7160

spring:
  application:
    name: hk-solr-web
  servlet:
    multipart:
      enabled: false
  mvc:
    formcontent:
      filter:
        enabled: false
  messages:
    encoding: UTF-8
    basename: messages
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration
      - org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration
  data:
    solr:
      host: http://47.107.245.220/solr/
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.40.18:8848
        namespace: eae427cd-ecb0-49fd-b3f1-999a0d68d2fe


logging:
  level:
    root: error
    com.hk.solr.web: info
    org.springframework.data.solr.core.SolrTemplate: debug
